### ISSUE TITLE
can you add a more simple example? 

### ISSUE THREAD

**Issue by ZhenFTW** [Wooyme/jfx-native-image-demo#1]
Like a button displaying a hello world something like that? I would really appreciate it if you do that.

**Comment by Wooyme** [comment]
Actually, the java code and fxml file are not so important. Even a very simple program needs much configuration when building native image.

**Comment by ZhenFTW** [comment]
Thanks for the reply. Im having trouble understanding the code could you tell me why you Load the dll in main.cpp? Is what you done build a client.dll in native image java and load the function in Main.cpp? Correct me if i'm wrong. Do you already try a better javafx gui with it? How's the performance? Sorry for that many question. Hope you could answer :). Coz right now there's no official way to build a native JAVAFX on graal.

**Comment by Wooyme** [comment]
You are right. At first, I thought loading client.dll from WinMain can avoid opening the console but it seems not to work.  So actually, it doesn't matter if u build a dynamic library or an executable program.

I think the performance right now is not really well because I have to disable some features supported by JavaFx  to build native image.

However, It's enough for me. All I want is to make my client startup quickly and take less memory. And the native image did well.
